apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCloud
metadata:
  name: example-zk-options
spec:
  replicas: 3
  solrImage:
    tag: 8.2.0
  zookeeperRef:
    provided:
      zookeeper:
        persistence:
          spec:
            storageClassName: "hostpath"
            resources:
              requests:
                storage: "5Gi"
        replicas: 1
        zookeeperPodPolicy:
          resources:
            limits:
              memory: "1G"
            requests:
              cpu: "65m"
              memory: "156Mi"
